FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY common/ common/
COPY attacker/ attacker/

ENV PYTHONPATH=/app

CMD ["python", "-m", "attacker.attacker", "--mode", "first_attack"]
